{
 "title": "jwt pizza service dashboard deliverable 8",
 "description": "main dashboard for jwt pizza deliverables",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "New Panel",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{level=\"info\"} |= `` | json"
    },
    {
     "expr": "{level=\"error\"} |= `` | json"
    },
    {
     "expr": "{service_name=\"unknown_service\"} |= `` | json"
    },
    {
     "expr": "{type=\"db\"} |= `` | json"
    },
    {
     "expr": "{type=\"exception\"} |= `` | json"
    },
    {
     "expr": "{type=\"factory\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(request_totalRequests{source=\"jwt-pizza-metrics2\"}[1m])",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "rate(request_delRequests{source=\"jwt-pizza-metrics2\"}[1m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(request_getRequests{source=\"jwt-pizza-metrics2\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(request_putRequests{source=\"jwt-pizza-metrics2\"}[1m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(request_postRequests{source=\"jwt-pizza-metrics2\"}[1m])",
     "legendFormat": "POST"
    }
   ]
  },
  {
   "title": "User Authentication Results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(request_successes{source=\"jwt-pizza-metrics2\"}[1m])",
     "legendFormat": "successes"
    },
    {
     "expr": "rate(request_failures{source=\"jwt-pizza-metrics2\"}[1m])",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": " Connection Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "request_pizzaCreationTime{source=\"jwt-pizza-metrics2\"}",
     "legendFormat": "pizza creation"
    },
    {
     "expr": "request_serviceLatency{source=\"jwt-pizza-metrics2\"}",
     "legendFormat": "service endpoints"
    }
   ]
  },
  {
   "title": "CPU and Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_cpuPercentage{source=\"jwt-pizza-metrcis2\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "request_memoryUsage{source=\"jwt-pizza-metrics2\"}",
     "legendFormat": "MEMORY"
    }
   ]
  },
  {
   "title": "Pizza's Sold and Pizza Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(request_pizzasSold{source=\"jwt-pizza-metrics2\"}[1m])",
     "legendFormat": "pizza sold per minute"
    },
    {
     "expr": "request_pizzaFailures{source=\"jwt-pizza-metrics2\"}",
     "legendFormat": "pizza creation failures"
    }
   ]
  },
  {
   "title": "Current Active User Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "request_activeUsers{source=\"jwt-pizza-metrics2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_revenue{source=\"jwt-pizza-metrics2\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}